# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matt Lovaglio
tagline:             'Articles, Theories & Ramblings'
description:         'A Personal Blog.'
url:                 http://www.mattlovaglio.com
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Matt Lovaglio
  url:               https://twitter.com/mattlovaglio
  email:             mattlovaglio@gmail.com

# Custom vars
version:             1.0.0
