# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matt Lovaglio
tagline:          'Articles, Theories & Ramblings'
description:      'A Personal Blog.'
url:              http://www.mattlovaglio.com
baseurl:          /

author:
  name:           'Matt Lovaglio'
  url:            https://twitter.com/mattlovaglio

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
